### ISSUE TITLE
How to configure in Nuxt 3?

### ISSUE THREAD

**Issue by matias-gmg** [nuxt-alt/proxy#13]
This configuration does not work in Nuxt 3:

```
export default defineNuxtConfig({
    modules: [
        '@nuxt-alt/proxy'
    ],
    proxy: {
        /* module options */
    }
});
```

Because the `proxy` property is not part of the `InputConfig<NuxtConfig, ConfigLayerMeta>` type.

How am I suppose to use this in Nuxt 3?

**Comment by matias-gmg** [comment]
Closing because I was able to configure it finally.

**Comment by KeironLowePatchWorks** [comment]
> Closing because I was able to configure it finally.

How did you fix it?
