### ISSUE TITLE
2.4.x update breaks proxy

### ISSUE THREAD

**Issue by Codermar** [nuxt-alt/proxy#16]
After upgrading to 2.4.2 from 2.3.2 proxy calls return 404 in the browser

log seems to indicate the calls are made though:
```
[dev] (Use `node --trace-warnings ...` to show where the warning was created)
[dev]   :okapi: 200 - http://local.com:8099/okapiapi/v1/profile
[dev] /okapiapi/v1/profile -> https://local.com:8087/api []
[1] Error: ENOENT: no such file or directory, stat '/app/dist/public/index.html'
[dev] [nitro-runtime] request: 0.037ms
[dev]   :okapi: 200 - http://local.com:8099/okapiapi/v1/config/ui
[dev] /okapiapi/v1/config/ui -> https://local.com:8087/api []
[1] Error: ENOENT: no such file or directory, stat '/app/dist/public/index.html'
[dev] [nitro-runtime] request: 0.027ms
[dev]   :okapi: 200 - http://local.com:8099/api/session
[dev] [nitro-runtime] beforeResponse: 0.009ms
[dev] [nitro-runtime] afterResponse: 0.009ms
[dev] [nitro-runtime] request: 0.107ms
[dev]   :okapi: 200 - http://local.com:8099/api/session
[dev] [nitro-runtime] beforeResponse: 0.005ms
[dev] [nitro-runtime] afterResponse: 0.008ms
```

Here's my config which works with 2.3.2: (I've tried several unsuccessful combinations with 2.4.2)

```
  proxy: {
    proxies: {
      // with options
      '/okapiapi': {
        target: `https://local.com:${process.env.API_PORT}/api`,
        changeOrigin: true,
        // NOTE: does not work with rewirte to just /api
        rewrite: (path: string) => path.replace(/^\/okapiapi/, ''),
        secure: false,
      },
    },
    experimental: {
      // fetch: false,
      importFunctions: false,
    },
  },
```

Nuxt version 3.8.1 (also tried nightly build)

**Comment by Denoder** [comment]
Does it not work with 2.4.0-2.4.1?
Try those versions and report back so I can see if there's any changes I need to make.

**Comment by Codermar** [comment]
Neither 2.4 version works.

**Comment by Denoder** [comment]
what's your full config?

**Comment by TimGuendel** [comment]
Same problem here 👀

**Comment by TimGuendel** [comment]
So I pinned the version to 2.3.2, but it still does not work - however some dependency under the hood must have changed so that the proxy returns 404. Here's the diff of my yarn.lock, if it helps:

https://www.textcompare.org/?id=655f316dca56ed4a039746b0

**Comment by Codermar** [comment]
@Denoder I did a little debugging and here are some hints for you:

this is the line that's producing the ENOENT error
```
proxy.web(event.node.req, event.node.res, options2);
```

In my case, the API has an authentication redirect which it would produce this line below `Error: ENOENT: no such file or directory, stat '/app/dist/public/index.html'` 

It looks like the code is not handling that redirect or it may also have to do with the fact I am using https. The API calls are being made because i can see the status of 200 (especially if `enableProxy: false` is set)

```
[dev] :::url true /okapiapi/v1/profile
[dev] /okapiapi/v1/profile :::->::: https://local.apple.com:8087/api []
[1] Error: ENOENT: no such file or directory, stat '/app/dist/public/index.html'
[dev]   :okapi: 200 - http://local.apple.com:8099/okapiapi/v1/config/ui
[dev]
[dev] :::url true /okapiapi/v1/config/ui
[dev] /okapiapi/v1/config/ui :::->::: https://local.apple.com:8087/api []
[1] Error: ENOENT: no such file or directory, stat '/app/dist/public/index.html'
[dev]   :okapi: 200 - http://local.apple.com:8099/api/session
[dev]   :okapi: 200 - http://local.apple.com:8099/api/session
```

**Comment by Denoder** [comment]
@Codermar I've released an update try that one.

**Comment by Codermar** [comment]
Excellent!. It's all good now with 2.4.3. Thank you for the quick response! @Denoder
