### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Quineone** [nuxt-alt/proxy#20]
"@nuxt-alt/proxy": "^2.2.3", or "@nuxt-alt/proxy": "^2.4.8"
Nuxt 3.8.2 with Nitro 2.8.1

Can be sure, there are memory leak. When add this module, the memory up is huge.

**Comment by Denoder** [comment]
You aren't providing enough info for me to do anything.

**Comment by Quineone** [comment]
Reproduce: 
1. create a new nuxt app project: `npx nuxi@latest init nuxt-app`,
2. add this module `yarn add @nuxt-alt/proxy`

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxt-alt/proxy'
  ],
})
```
in  package.json
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "debug": "node --inspect .output/server/index.mjs",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.8.2",
    "vue": "^3.3.12",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxt-alt/proxy": "^2.4.8"
  }
}
```
3. run `yarn build`, aftern done, run `yarn debug`
4. open `chrome://inspect` in chrome, and click inspect
![image](https://github.com/nuxt-alt/proxy/assets/15320933/62e142ec-857c-4a52-8a7d-99068c97e89d)
5. click `Take snapshot`
![image](https://github.com/nuxt-alt/proxy/assets/15320933/0cec7be3-0754-49bb-a6d2-77646c8976ef)
6. open another termimal, run `loadtest -n 100 http://localhost:3000` (need install loadtest first: [hereby](https://github.com/alexfernandez/loadtest))
7. click `Take snapshot` agian,
5. after repeat step 6 and step 7 for multiple times, you can see the memory increase each time
![image](https://github.com/nuxt-alt/proxy/assets/15320933/3c319827-8a88-49ff-b9fc-f01145fb56c9)

**Comment by Quineone** [comment]
you can disable this module 
```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  // modules: [
  //   '@nuxt-alt/proxy'
  // ],
})
```
and test again, and the result would be look like:
![image](https://github.com/nuxt-alt/proxy/assets/15320933/e91b2755-3853-4c86-b7d8-9817ee95bc77)

**Comment by Denoder** [comment]
@Quineone I've updated the proxy package that it uses can you try to update and see if that fixes it for you?
