### ISSUE TITLE
crypto is not defined

### ISSUE THREAD

**Issue by IvanWala** [nuxt-alt/proxy#22]
Hi we reinstall Nuxt and the packages from a project and we find this issue.

```
 ERROR  Cannot restart nuxt:  crypto is not defined

  at /node_modules/@refactorjs/serialize/dist/index.mjs:1:18
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

The only package with this dependencie is nuxt-alt/proxy. Can someone help us?

**Comment by IvanWala** [comment]
Is working downgrading to 2.4.9

**Comment by Denoder** [comment]
I've updated the underlying package can you check to see if that works for you?
