### ISSUE TITLE
WS connection proxying to the nestjs gateway

### ISSUE THREAD

**Issue by NonOrganicCreature** [nuxt-alt/proxy#8]
I am trying to proxy socket-io client to the nestjs WS gateway .
Here is the config of the module
``` 
 proxy: {
    enableProxy: true,
    // fetch: true,
    proxies: {
      // with options
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
      '/socket.io': {
        target: 'ws://localhost:3010',
        changeOrigin: true,
        ws: true,
      },
    },
  },
  ```
Nuxt server is working at http://localhost:3005. 
```
const socket = io({ transports: ['websocket'] })
```
Connection from vue component.

Nest js gateway running under 3010 port and also has transports: ['websocket'].

```
@WebSocketGateway(3010, {
  transports: ['websocket'],
})
```
But i could not connect to nestjs gateway and got this warning:
```
WebSocket connection to 'ws://localhost:3005/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed before the connection is established.
```
Nuxt server logs:
```
/socket.io/?EIO=4&transport=websocket -> ws://localhost:3010 
```

If i switch transport from websocket to polling both server and client side, config works fine.
How to configure plugin properly in that case?

**Comment by codaxiom** [comment]
@NonOrganicCreature Did you find a way to use websocket ?

I'm using the same config, but only polling transport works..
